stages:
  - deploy

image:
  name: jdxcode/mise:2025.9.6
  entrypoint: [""]

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules
    - .task
    - .turbo
    - .mise
  policy: pull-push

before_script:
  - mise install

pages:
  stage: deploy
  only:
    - main
  environment:
    name: preview
    url: https://${CI_PROJECT_NAMESPACE}.pages.s-v.de/${CI_PROJECT_TITLE}
  pages:
    publish: dist
  script: task build
