#!/bin/bash

# resolve template variables

envsubst < package.json > package.json.tmp && mv package.json.tmp package.json
envsubst < README.md > README.md.tmp && mv README.md.tmp README.md

# pin all dependencies

mise use task@latest --pin
mise use bun@latest --pin

bun add @types/bun@latest

# clean setup script

rm $0
